Repository ecmwf/WeatherGenerator, pull requests merged in 2025-08, with the labels that each got.

#496 Implement global and per-cell channel masking
  config/default_config.yml
  src/weathergen/datasets/masking.py
  src/weathergen/datasets/multi_stream_data_sampler.py
  src/weathergen/datasets/tokenizer_masking.py
Labels: enhancement, model

#785 Work around to allow for model freezing
  src/weathergen/train/trainer.py
Labels: bug

#794 Modify DataReaderObs to get base_yyyy... from stream config
  config/streams/igra/igra.yml
  src/weathergen/datasets/data_reader_obs.py
Labels: bug, enhancement, datasets

#803 Train continue function with arguments
  src/weathergen/run_train.py
Labels: enhancement

#826 Iluise/fix empty io 819 plotting
  packages/common/src/weathergen/common/io.py
  packages/evaluate/src/weathergen/evaluate/plotter.py
  packages/evaluate/src/weathergen/evaluate/utils.py
Labels: evaluation

#828 fix plotting for partially filled forecast steps
  packages/evaluate/src/weathergen/evaluate/utils.py
Labels: evaluation
