Repository ecmwf/WeatherGenerator, pull requests merged in 2025-09, with the labels that each got.

#853 Fix calculation of scores per fstep
  packages/evaluate/src/weathergen/evaluate/utils.py
Labels: bug

#815 add tokenizer base class
  src/weathergen/datasets/tokenizer.py
  src/weathergen/datasets/tokenizer_forecast.py
  src/weathergen/datasets/tokenizer_masking.py
Labels: quality

#798 Implement causal masking as MTM strategy
  config/default_config.yml
  config/streams/era5_1deg/era5.yml
  src/weathergen/datasets/masking.py
Labels: enhancement, model

#927 [926][evaluation] weatherGen reader for evaluation package
  packages/evaluate/src/weathergen/evaluate/io_reader.py
  packages/evaluate/src/weathergen/evaluate/run_evaluation.py
Labels: evaluation

#964 fix error when global_plotting_opt does not exist
  packages/evaluate/src/weathergen/evaluate/run_evaluation.py
Labels: evaluation
