Repository ecmwf/WeatherGenerator, pull requests merged in 2025-10, with the labels that each got.

#959 Sophiex/dev/fsdp2 fix
  packages/common/src/weathergen/common/config.py
  packages/common/src/weathergen/common/io.py
  src/weathergen/datasets/data_reader_anemoi.py
  src/weathergen/datasets/data_reader_obs.py
  src/weathergen/datasets/multi_stream_data_sampler.py
  src/weathergen/datasets/stream_data.py
  src/weathergen/datasets/tokenizer_forecast.py
  src/weathergen/datasets/tokenizer_masking.py
  src/weathergen/model/ema.py
  src/weathergen/model/embeddings.py
  src/weathergen/model/engines.py
  src/weathergen/model/model.py
  src/weathergen/run_train.py
  src/weathergen/train/loss_calculator.py
  src/weathergen/train/lr_scheduler.py
  src/weathergen/train/trainer.py
  src/weathergen/train/trainer_base.py
  src/weathergen/utils/distributed.py
  src/weathergen/utils/logger.py
  src/weathergen/utils/train_logger.py
Labels: model

#753 Channel weighting in loss computation
  config/streams/era5_1deg/era5.yml
  src/weathergen/datasets/data_reader_anemoi.py
  src/weathergen/datasets/data_reader_base.py
  src/weathergen/datasets/multi_stream_data_sampler.py
  src/weathergen/train/loss.py
  src/weathergen/train/loss_calculator.py
Labels: enhancement, model

#1057 Fix CERRA eval breaking with coord sorting in `froct`
  packages/evaluate/src/weathergen/evaluate/score.py
  packages/evaluate/src/weathergen/evaluate/utils.py
Labels: evaluation

#1060 [1059][eval] Fix eval crash of inference models from other HPCs
  packages/common/src/weathergen/common/config.py
  packages/evaluate/src/weathergen/evaluate/io_reader.py
Labels: evaluation
