Repository ecmwf/WeatherGenerator, pull requests merged in 2025-04, with the labels that each got.

#171 Misc fixes
  src/weathergen/datasets/multi_stream_data_sampler.py
  src/weathergen/model/model.py
  src/weathergen/train/trainer.py
Labels: bug

#159 Sgrasse/develop/issue 106
  config/default_config.yml
  pyproject.toml
  src/weathergen/__init__.py
  src/weathergen/train/trainer.py
  src/weathergen/train/trainer_base.py
  src/weathergen/utils/config.py
  src/weathergen/utils/plot_training.py
  src/weathergen/utils/train_logger.py
  uv.lock
Labels: enhancement

#156 preliminary test script for the WeatherGenerator
  config/default_config.yml
  config/streams/streams_test/era5.yml
  integration_tests/small1.py
  integration_tests/small1.yaml
  pyproject.toml
  src/weathergen/__init__.py
  src/weathergen/train/trainer.py
  src/weathergen/utils/config.py
  uv.lock
Labels: quality
